version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes: 
      - ./db/db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "${DB_PORT}:5432"

  fastapi:
    build:
      context: ./order_service
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=0
    ports:
      - 80:80