"""Created statistic, fixed table name

Revision ID: 776c5da55a30
Revises: 6a834e369c21
Create Date: 2023-08-16 14:54:16.307815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '776c5da55a30'
down_revision: Union[str, None] = '6a834e369c21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statistic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('total_order_price', sa.DECIMAL(), nullable=False),
    sa.Column('avg_order_price', sa.Float(), nullable=False),
    sa.Column('total_items', sa.Integer(), nullable=False),
    sa.Column('avg_items', sa.Float(), nullable=False),
    sa.Column('most_ordered_item', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('items')
    op.alter_column('order', 'created_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('order', 'updated_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('order', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('order', 'total',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'total',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('order', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('order', 'updated_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('order', 'created_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_table('items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name='items_order_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='items_pkey')
    )
    op.drop_table('item')
    op.drop_table('statistic')
    # ### end Alembic commands ###
